[formatter."c++"]
command = "clang-format"
options = [
  "-i",
  "-style",
  "{BasedOnStyle: llvm, IndentWidth: 4, SortIncludes: false}"
]
includes = ["*.c", "*.cpp", "*.cc", "*.h", "*.hpp"]

[formatter.nix]
command = "nixpkgs-fmt"
includes = ["*.nix"]

[formatter.toml]
command = "prettier"
options = ["--write"]
includes = ["*.toml"]
