[formatter.nix]
command = "nixfmt"
includes = ["*.nix"]
excludes = ["tests/**"]

[formatter.ruff-format]
command = "ruff"
options = ["format"]
includes = ["tests/functional2/**/*.py", "meson/clang-tidy/*.py"]
priority = 0

[formatter.ruff]
command = "ruff"
options = ["check"]
includes = ["tests/functional2/**/*.py", "meson/clang-tidy/*.py", "maintainers/*.py", "lix/code-generation/*.py"]
priority = 1
